### PR TITLE
fix(ci): pin Flutter to 3.41.9 — flutter_quill 11.5.0 incompatible with 3.44.0

### PR DESCRIPTION
**Pull request by Mark-Yun**
Scheduler: swe-sonnet-1

## Summary

Flutter 3.44.0이 \`TextInputClient.onFocusReceived()\`를 추가했으나 flutter_quill 11.5.0이 구현하지 않아, 모든 Flutter 앱 PR CI가 실패 중입니다.

**Root cause**: Flutter 3.44.0 added \`bool onFocusReceived() => false;\` to \`TextInputClient\`, requiring all \`TextInputClient\` implementors to implement it. flutter_quill's \`RawEditorStateTextInputClientMixin\` does not implement this method.

**Fix**: Pin Flutter to 3.41.9 (last stable before 3.44.0). flutter_quill 11.5.0 works correctly with 3.41.9.

**Upstream tracking**: singerdmx/flutter-quill#2726 (open PR adding the method)

## 영향 범위

7개 workflow 파일, 10곳 변경:
- `pr-gate.yml` (4곳)
- `shared-cuj-integration.yml` (1곳)  
- `shared-android-deploy.yml` (1곳)
- `monitor-patrol-e2e.yml` (1곳)
- `sync-test-coverage.yml` (1곳)
- `monitor-mds-render-coverage.yml` (1곳)
- `monitor-cuj-coverage.yml` (1곳)

## 검증 방법

- Flutter 3.41.9에서 \`onFocusReceived\` 미존재 확인: `curl -s "https://raw.githubusercontent.com/flutter/flutter/3.41.9/packages/flutter/lib/src/services/text_input.dart" | grep onFocusReceived` → 결과 없음
- Flutter 3.44.0에서 존재 확인: 1401번 줄에 \`bool onFocusReceived() => false;\`

## Rollback 계획

flutter_quill 11.5.x 이상에서 fix가 배포되면:
1. 이 PR과 반대 방향으로 \`flutter-version: '3.41.9'\`를 \`channel: 'stable'\`로 되돌림
2. singerdmx/flutter-quill#2726 머지 모니터링

Closes #2640

### CODE REVIEW

File: .github/workflows/monitor-cuj-coverage.yml [hunk 1]
```diff
@@ -24,7 +24,7 @@ jobs:
 
       - uses: subosito/flutter-action@v2
         with:
-          channel: 'stable'
```
Comment (EchoEllet) [inline .github/workflows/monitor-cuj-coverage.yml:27]: This issue has been addressed now, so feel free to revert.
(You should still pin Flutter verison regardless of Flutter Quill)
